language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - wget https://raw.githubusercontent.com/WildCoastSolutions/UnitTesting/master/UnitTesting.h -O ./Test/UnitTesting.h

install:
  - cmake .
  - make

script:
  - ./Test/CommandLineTest